// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package customTypes

type InputRole struct {
	Name  string   `json:"name"`
	Users []string `json:"users"`
}

type NewRole struct {
	Name      string `json:"name"`
	ProjectID string `json:"projectID"`
}

type NewUser struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Mail      string `json:"mail"`
	Password  string `json:"password"`
}

type PasswordUpdate struct {
	UserID   string `json:"userID"`
	Password string `json:"password"`
}

type Project struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Roles     []*Role `json:"roles"`
	Users     []*User `json:"users"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type ProjectInput struct {
	Name  string   `json:"name"`
	Roles []string `json:"roles"`
	Users []string `json:"users"`
}

type Role struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	ProjectID string  `json:"projectID"`
	Users     []*User `json:"users"`
}

type UpdateUser struct {
	FirstName string   `json:"firstName"`
	LastName  string   `json:"lastName"`
	Mail      string   `json:"mail"`
	Projects  []string `json:"projects"`
	Roles     []string `json:"roles"`
}

type User struct {
	ID        string     `json:"id"`
	FirstName string     `json:"firstName"`
	LastName  string     `json:"lastName"`
	Mail      string     `json:"mail"`
	Password  string     `json:"password"`
	Projects  []*Project `json:"projects"`
	Roles     []*Role    `json:"roles"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
}
