package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"dabids/graph/customTypes"
	"fmt"
)

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input customTypes.NewRole) (*customTypes.Role, error) {
	panic(fmt.Errorf("not implemented: CreateRole - createRole"))
}

// UdpateRole is the resolver for the udpateRole field.
func (r *mutationResolver) UdpateRole(ctx context.Context, input customTypes.InputRole) (*customTypes.Role, error) {
	panic(fmt.Errorf("not implemented: UdpateRole - udpateRole"))
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, roleID string) (*customTypes.Role, error) {
	panic(fmt.Errorf("not implemented: DeleteRole - deleteRole"))
}

// GetRole is the resolver for the getRole field.
func (r *queryResolver) GetRole(ctx context.Context, roleID string) (*customTypes.Role, error) {
	panic(fmt.Errorf("not implemented: GetRole - getRole"))
}

// GetRoles is the resolver for the getRoles field.
func (r *queryResolver) GetRoles(ctx context.Context) ([]*customTypes.Role, error) {
	panic(fmt.Errorf("not implemented: GetRoles - getRoles"))
}
